services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lembrete-api'
      - 'POSTGRES_PASSWORD=AdrianoVictor159@'
      - 'POSTGRES_USER=DevAdrianoLembrete'
    ports:
      - '5432'
  
  pgadmin4:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=adrianovictorads@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=AdrianoVictor159@'
    ports:
      - '15432:80'
  backend:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - postgres